const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),QRCode=require('qrcode');
const PORT=Number(process.env.PORT||8080),HOST=process.env.HOST||'0.0.0.0',PIN=process.env.ADMIN_PIN||(process.env.NODE_ENV==='production'?null:'3141');if(!PIN)throw Error('Defina ADMIN_PIN.');
const PUBLIC=path.join(__dirname,'public'),DATA=path.join(process.env.DATA_DIR||path.join(__dirname,'data'),'tournament.json'),clients=new Set();
const uid=p=>p+crypto.randomUUID().slice(0,8),room=()=>crypto.randomBytes(3).toString('hex').toUpperCase();
const fresh=()=>({roomCode:room(),status:'setup',config:{title:'Torneio 4 em Linha',rounds:5,variant:'classic',deviceMode:'individual'},players:[],rounds:[],currentRound:0,message:'Inscrições abertas'});
let state=(()=>{try{return JSON.parse(fs.readFileSync(DATA,'utf8'))}catch{return fresh()}})();
function save(){fs.mkdirSync(path.dirname(DATA),{recursive:true});const t=DATA+'.tmp';fs.writeFileSync(t,JSON.stringify(state,null,2));fs.renameSync(t,DATA)}
const player=id=>state.players.find(p=>p.id===id),matches=()=>state.rounds[state.currentRound-1]?.matches||[],board=()=>Array.from({length:6},()=>Array(7).fill(null));
function rank(){return state.players.map(p=>({...p,buchholz:p.opponents.reduce((n,id)=>n+(player(id)?.points||0),0)})).sort((a,b)=>b.points-a.points||b.buchholz-a.buchholz||b.wins-a.wins||a.name.localeCompare(b.name,'pt'))}
function apply(m){if(m.applied)return;m.applied=true;if(m.bye){const p=player(m.winner);p.points++;p.wins++;p.bye=true}else if(m.draw){[m.red,m.yellow].forEach(id=>{const p=player(id);p.points+=.5;p.draws++})}else{const w=player(m.winner),l=player(m.winner===m.red?m.yellow:m.red);w.points++;w.wins++;l.losses++}const r=state.rounds.find(r=>r.matches.includes(m));r.complete=r.matches.every(x=>x.status==='finished');if(r.complete&&state.currentRound>=state.config.rounds)state.status='finished'}
function balance(p,c){const r=p.colours.filter(x=>x==='red').length;return c==='red'?r-(p.colours.length-r):(p.colours.length-r)-r}
function pairRound(){let pool=rank().map(x=>player(x.id)),out=[];if(pool.length%2){const b=[...pool].reverse().find(p=>!p.bye)||pool.at(-1);pool=pool.filter(p=>p.id!==b.id);out.push({id:uid('m_'),red:b.id,yellow:null,board:board(),cells:[],turn:null,status:'finished',winner:b.id,draw:false,bye:true})}while(pool.length){const a=pool.shift();let i=pool.findIndex(b=>!a.opponents.includes(b.id));if(i<0)i=0;let b=pool.splice(i,1)[0],red=a,yellow=b;if(balance(a,'red')>balance(b,'red'))[red,yellow]=[b,a];const m={id:uid('m_'),red:red.id,yellow:yellow.id,board:board(),cells:[],turn:red.id,status:'playing',winner:null,draw:false,bye:false,sharedToken:null};out.push(m);red.opponents.push(yellow.id);yellow.opponents.push(red.id);red.colours.push('red');yellow.colours.push('yellow')}state.currentRound++;state.rounds.push({number:state.currentRound,matches:out,complete:out.every(m=>m.status==='finished')});state.status='playing';out.filter(m=>m.bye).forEach(apply)}
function four2(b,r,c,k){for(const[dR,dC]of[[0,1],[1,0],[1,1],[1,-1]]){let n=1;for(const s of[-1,1]){let y=r+dR*s,x=c+dC*s;while(y>=0&&y<6&&x>=0&&x<7&&b[y][x]===k){n++;y+=dR*s;x+=dC*s}}if(n>=4)return true}return false}
function four3(cells,q){const at=new Map(cells.map(c=>[`${c.x}-${c.y}-${c.z}`,c.colour]));for(let dx=-1;dx<=1;dx++)for(let dy=-1;dy<=1;dy++)for(let dz=-1;dz<=1;dz++){if(!dx&&!dy&&!dz||dx<0||(!dx&&dy<0)||(!dx&&!dy&&dz<0))continue;let n=1;for(const s of[-1,1]){let x=q.x+dx*s,y=q.y+dy*s,z=q.z+dz*s;while(x>=0&&x<4&&y>=0&&y<4&&z>=0&&z<4&&at.get(`${x}-${y}-${z}`)===q.colour){n++;x+=dx*s;y+=dy*s;z+=dz*s}}if(n>=4)return true}return false}
function view(){return {...state,players:state.players.map(({token,...p})=>({...p,claimed:!!token})),standings:rank().map(({token,...p},i)=>({...p,rank:i+1})),rounds:state.rounds.map(r=>({...r,matches:r.matches.map(({sharedToken,...m})=>({...m,sharedClaimed:!!sharedToken}))}))}}
function send(res,n,x,h={}){res.writeHead(n,{'Content-Type':'application/json; charset=utf-8',...h});res.end(JSON.stringify(x))}function body(req){return new Promise((ok,no)=>{let s='';req.on('data',c=>{s+=c;if(s.length>1e5)req.destroy()});req.on('end',()=>{try{ok(s?JSON.parse(s):{})}catch(e){no(e)}})})}function admin(req,res){if(req.headers['x-admin-pin']!==PIN){send(res,401,{error:'PIN do professor incorreto.'});return false}return true}function broadcast(){const x=`data: ${JSON.stringify(view())}\n\n`;for(const r of clients)try{r.write(x)}catch{clients.delete(r)}}
async function api(req,res,url){if(req.method==='GET'&&url.pathname==='/api/state')return send(res,200,view(),{'Cache-Control':'no-store'});if(req.method==='GET'&&url.pathname==='/api/qr'){const u=url.searchParams.get('url');if(!/^https?:\/\//.test(u||''))return send(res,400,{error:'Endereço inválido.'});const svg=await QRCode.toString(u,{type:'svg',margin:1,width:300});res.writeHead(200,{'Content-Type':'image/svg+xml'});return res.end(svg)}if(req.method==='GET'&&url.pathname==='/events'){res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-cache',Connection:'keep-alive'});res.write(`data: ${JSON.stringify(view())}\n\n`);clients.add(res);req.on('close',()=>clients.delete(res));return}const b=await body(req);
  if(req.method==='POST'&&url.pathname==='/api/admin/new'){if(!admin(req,res))return;state=fresh();save();broadcast();return send(res,200,view())}
  if(req.method==='POST'&&url.pathname==='/api/admin/config'){if(!admin(req,res))return;if(state.status!=='setup')return send(res,409,{error:'Crie um torneio novo para alterar a configuração.'});state.config={title:String(b.title||'Torneio 4 em Linha').slice(0,60),rounds:Math.max(1,Math.min(15,+b.rounds||5)),variant:b.variant==='spatial'?'spatial':'classic',deviceMode:b.deviceMode==='shared'?'shared':'individual'};save();broadcast();return send(res,200,view())}
  if(req.method==='POST'&&url.pathname==='/api/admin/remove'){if(!admin(req,res))return;if(state.status!=='setup')return send(res,409,{error:'Só é possível remover inscrições antes do início.'});state.players=state.players.filter(p=>p.id!==b.playerId);save();broadcast();return send(res,200,view())}
  if(req.method==='POST'&&url.pathname==='/api/admin/start'){if(!admin(req,res))return;if(state.players.length<2)return send(res,400,{error:'São necessários pelo menos 2 jogadores.'});pairRound();save();broadcast();return send(res,200,view())}
  if(req.method==='POST'&&url.pathname==='/api/admin/next'){if(!admin(req,res))return;const r=state.rounds.at(-1);if(!r?.complete)return send(res,409,{error:'Ainda há partidas por terminar.'});if(state.currentRound>=state.config.rounds)return send(res,409,{error:'O torneio terminou.'});pairRound();save();broadcast();return send(res,200,view())}
  if(req.method==='POST'&&url.pathname==='/api/admin/draw'){if(!admin(req,res))return;const m=matches().find(x=>x.id===b.matchId);if(!m||m.status==='finished')return send(res,400,{error:'Partida inválida.'});m.status='finished';m.draw=true;apply(m);save();broadcast();return send(res,200,view())}
  if(req.method==='POST'&&url.pathname==='/api/register'){if(String(b.roomCode||'').toUpperCase()!==state.roomCode)return send(res,400,{error:'Código do torneio incorreto.'});if(state.status!=='setup')return send(res,409,{error:'As inscrições já terminaram.'});const name=String(b.name||'').trim().replace(/\s+/g,' ').slice(0,30),token=String(b.token||'');if(name.length<2)return send(res,400,{error:'Escreve um nome entre 2 e 30 caracteres.'});if(!token)return send(res,400,{error:'Ligação inválida.'});if(state.players.some(p=>p.name.toLocaleLowerCase('pt')===name.toLocaleLowerCase('pt')))return send(res,409,{error:'Esse nome já está inscrito.'});const p={id:uid('p_'),name,token,points:0,wins:0,draws:0,losses:0,opponents:[],colours:[],bye:false};state.players.push(p);save();broadcast();return send(res,200,{playerId:p.id,state:view()})}
  if(req.method==='POST'&&url.pathname==='/api/join-table'){if(String(b.roomCode||'').toUpperCase()!==state.roomCode)return send(res,400,{error:'Código incorreto.'});const m=matches().find(x=>x.id===b.matchId&&!x.bye),token=String(b.token||'');if(!m||!token)return send(res,400,{error:'Mesa inválida.'});if(m.sharedToken&&m.sharedToken!==token)return send(res,409,{error:'Mesa já aberta.'});m.sharedToken=token;save();broadcast();return send(res,200,view())}
  if(req.method==='POST'&&url.pathname==='/api/drop'){const m=matches().find(x=>x.id===b.matchId),token=String(b.token||''),shared=state.config.deviceMode==='shared'&&m?.sharedToken===token,p=shared?player(m?.turn):state.players.find(x=>x.token===token);if(!m||!p||m.status!=='playing'||m.turn!==p.id)return send(res,400,{error:'Jogada inválida.'});const colour=p.id===m.red?'red':'yellow';if(state.config.variant==='spatial'){const x=+b.x,z=+b.z,y=m.cells.filter(c=>c.x===x&&c.z===z).length;if(x<0||x>3||z<0||z>3||y>3)return send(res,400,{error:'Pilar inválido.'});const q={x,y,z,colour};m.cells.push(q);if(four3(m.cells,q)){m.status='finished';m.winner=p.id;apply(m)}else if(m.cells.length===64){m.status='finished';m.draw=true;apply(m)}else m.turn=p.id===m.red?m.yellow:m.red}else{const c=+b.column;let r=5;if(c<0||c>6)return send(res,400,{error:'Coluna inválida.'});while(r>=0&&m.board[r][c])r--;if(r<0)return send(res,400,{error:'Coluna cheia.'});m.board[r][c]=colour;if(four2(m.board,r,c,colour)){m.status='finished';m.winner=p.id;apply(m)}else if(m.board.every(row=>row.every(Boolean))){m.status='finished';m.draw=true;apply(m)}else m.turn=p.id===m.red?m.yellow:m.red}save();broadcast();return send(res,200,view())}return send(res,404,{error:'Rota inexistente.'})}
function staticFile(res,url){const req=url.pathname==='/'?'/index.html':url.pathname,target=path.normalize(path.join(PUBLIC,req));if(!target.startsWith(PUBLIC))return send(res,403,{error:'Acesso negado.'});fs.readFile(target,(e,d)=>{if(e)return send(res,404,{error:'Ficheiro não encontrado.'});const t={'.html':'text/html; charset=utf-8','.css':'text/css','.js':'text/javascript; charset=utf-8','.webmanifest':'application/manifest+json'}[path.extname(target)]||'application/octet-stream';res.writeHead(200,{'Content-Type':t,'Cache-Control':'no-cache'});res.end(d)})}
const server=http.createServer((req,res)=>{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);Promise.resolve(url.pathname.startsWith('/api/')||url.pathname==='/events'?api(req,res,url):staticFile(res,url)).catch(e=>{console.error(e);if(!res.headersSent)send(res,500,{error:'Erro interno.'})})});if(require.main===module)server.listen(PORT,HOST,()=>console.log(`4 em Linha: ${PORT}`));module.exports={four2,four3,server,fresh};
